#!/bin/sh
echo "Preparing Sandbox..."

TEMP=`tempfile`

cd $1
# server
tar -hczf $TEMP *
tar -xzf $TEMP --directory $2 
cd ..

# /dev
tar -czf $TEMP /dev/null /dev/random /dev/urandom 
tar -xzf $TEMP --directory $2

# etc
tar -czf $TEMP /etc/resolv.conf
tar -xzf $TEMP --directory $2

# libs
tar -czf $TEMP /lib/libgcc_s.so.1
tar -xzf $TEMP --directory $2

rm $TEMP
